language: rust

before_install:
  - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -

matrix:
  include:
    - os: linux
      rust: stable

script:
    - rustup component add llvm-tools-preview
    - export NO_SUPPORTED_PORTS=1
    - cargo build --verbose
    - cargo xtask coverage
    - bash <(curl -s https://codecov.io/bash) -f coverage/tests.lcov
